### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by iva-stasia** [Fedor-sherbanyuk/bulma3#3]
In general, the app looks pretty good, but I have a few recommendations.

First, some recommendations about the application.

- When the checkbox is checked, only those questions that have not yet been studied should remain.
![image](https://user-images.githubusercontent.com/110097862/227907041-db5c8109-04d5-465a-aeea-ba04efaabbd2.png)

- When I add a new question, I have a bug with numbering. At the same time, a new question is duplicated at the end of the list.
Also, pay attention to the different spacing between the added questions and those that were in the original database.
![image](https://user-images.githubusercontent.com/110097862/227906786-2275979d-ff8c-4306-8d03-02a1954185bd.png)

- I think it would be a good idea to add a cursor pointer for the status because it is a clickable element.

- Since the whole page is in English, wouldn't it be better to make the placeholder and the button in English as well?

Next, about the code.

- File names. A name like `file.js` doesn't say much. Wouldn't it be better to use something like `dataset.js`? The same for `functionJs.js`. This file doesn't contain one specific function, but it executes the basic logic. Could it be, for example, `main.js` or `index.js`?

- In the list of questions, the status value is a number. Isn't it better to use boolean values in such a case? This will make the code easier to read and help avoid possible bugs.
```javascript
{question: "Explain event delegation.", status: true}
// instead of
{question: "Explain event delegation.", status: 1}
```

- I suggest you look at the naming [guideline](https://www.30secondsofcode.org/articles/s/javascript-naming-conventions/) and try to improve the naming in your code. For example, such names as `obj`, `display()`, `statusQuestion()` don't say much.

- The block with the title in the `display()` is static, it does not change during the operation of the program, so you can insert it into the markup immediately, without using the JS for this.
https://github.com/Fedor-sherbanyuk/bulma3/blob/71d0af7f0fb633b141b92528cfcb832c66b60a10/functionJs.js#L5

- Your markup doesn't have any element with the `.card-list` class, so what should happen if the length of the array is 1?
https://github.com/Fedor-sherbanyuk/bulma3/blob/71d0af7f0fb633b141b92528cfcb832c66b60a10/functionJs.js#L14-L19

- Pay attention to this line, it is the reason for incorrect numbering when adding a new question. At the same time, a new question is duplicated at the end of the list.
https://github.com/Fedor-sherbanyuk/bulma3/blob/71d0af7f0fb633b141b92528cfcb832c66b60a10/functionJs.js#L58
If you want to post a new question first, you will have to re-render all the questions to change their numbers. It is also logical to use the `reverse()` method.

- The array must be filtered in the `filterAnswer()` function, because the data may change between clicking the checkbox and the current version of the array must be filtered. Also note that we need questions that have not yet been studied.
https://github.com/Fedor-sherbanyuk/bulma3/blob/71d0af7f0fb633b141b92528cfcb832c66b60a10/functionJs.js#L3

- Instead of the `subscribe()` function, I suggest you consider the [event delegation pattern](https://javascript.info/event-delegation). This is much better than creating an event listener for each individual card. It also eliminates the need to re-subscribe after each update.
For example, it can be like this:
```javascript
document.querySelector('#cardNew').addEventListener('click', (e) => changeStatus(e));

function changeStatus(event) {
    if (event.target.closest('span[data-id]')) {
        // change status
    }
}
```

**Comment by Fedor-sherbanyuk** [comment]
Everything changed that was required in the check
